Update patch set 1
Patch Set 1:

(2 comments)

[ 05-25 23:28:23.032  9942: 9953 W/System.err ]
java.io.IOException: Cannot run program "/data/system/theme/bin": error=13, Permission denied

[ 05-25 23:28:23.033  9942: 9953 W/System.err ]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:983)

[ 05-25 23:28:23.033  9942: 9953 W/System.err ]
        at java.lang.Runtime.exec(Runtime.java:691)

[ 05-25 23:28:23.033  9942: 9953 W/System.err ]
        at java.lang.Runtime.exec(Runtime.java:559)

[ 05-25 23:28:23.033  9942: 9953 W/System.err ]
        at com.slimroms.omsbackend.OmsBackendService.compileOverlay(OmsBackendService.java:715)

[ 05-25 23:28:23.033  9942: 9953 W/System.err ]
        at com.slimroms.omsbackend.OmsBackendService.-wrap0(OmsBackendService.java)

[ 05-25 23:28:23.033  9942: 9953 W/System.err ]
        at com.slimroms.omsbackend.OmsBackendService$Helper.installOverlaysFromTheme(OmsBackendService.java:487)

[ 05-25 23:28:23.033  9942: 9953 W/System.err ]
        at com.slimroms.themecore.IThemeService$Stub.onTransact(IThemeService.java:114)

[ 05-25 23:28:23.037  9942: 9953 W/System.err ]
        at android.os.Binder.execTransact(Binder.java:565)

[ 05-25 23:28:23.039  9942: 9953 W/System.err ]
Caused by: java.io.IOException: error=13, Permission denied

[ 05-25 23:28:23.039  9942: 9953 W/System.err ]
        at java.lang.UNIXProcess.forkAndExec(Native Method)

[ 05-25 23:28:23.039  9942: 9953 W/System.err ]
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)

[ 05-25 23:28:23.039  9942: 9953 W/System.err ]
        at java.lang.ProcessImpl.start(ProcessImpl.java:128)

[ 05-25 23:28:23.039  9942: 9953 W/System.err ]
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:964)

[ 05-25 23:28:23.039  9942: 9953 W/System.err ]
        ... 7 more


Notes for tomorrow, late tired etc etc.

Patch-set: 1
Label: Verified=0